Device/urls.py
from django.urls import path
from Device.viewslist import views_device, views_login, views_home, views_admin, views_customer
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #--- 申請一覧 ---#
    path('', views_login.login, name='login'),

    path('home_admin/<int:struserid>/', views_home.home_admin, name='home_admin'),

    path('home_customer/<int:struserid>/', views_home.home_customer, name='home_customer'),

    path('detail_device/<int:struserid>/<int:strdevid>', views_device.detail_device, name='detail_device'),

    path('manage_admin/<int:struserid>/', views_admin.manage_admin, name='manage_admin'),

    path('manage_device/<int:struserid>/', views_device.manage_device, name='manage_device'),

    path('create_device/<int:struserid>/', views_device.create_device, name='create_device'),

    path('edit_device/<int:struserid>/<int:strdevid>/', views_device.edit_device, name='edit_device'),

    path('manage_customer/<int:struserid>/', views_customer.manage_customer, name='manage_customer'),

] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ManageDevice/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Device.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Device/models.py
from django.db import models

#------------------------------------------------------------------------------------------------#

#ユーザーマスタ

class UserMst(models.Model):

    
    usrLoginID          = models.CharField( max_length = 15 )                               #ログインID

    usrName             = models.CharField( max_length = 15 )                               #ユーザー名

    usrPassWord         = models.CharField( max_length = 15 )                               #パスワード
    
    usrKind             = models.IntegerField( choices = [( 1, '顧客' ),
                                                          ( 2, '管理者'),
                                                        ] 
                                        )                                                   #ユーザー種別
    
    usrDelete           = models.BooleanField( default = False )                            #削除フラグ
    
    usrMail             = models.CharField( max_length = 30, null = True, blank = True )    #メールアドレス
    
    usrCustomer         = models.CharField( max_length = 30, null = True, blank = True )    #顧客名

    # 顧客プロフィール画像（1枚だけ）
    usrDeviceMap = models.ImageField(upload_to='device_maps/', null=True, blank=True)

    def __str__(self):
        return str( self.id ) + '[' + str( self.usrDelete ) +']' + (self.usrName if self.usrName else self.usrCustomer)
    
class DeviceMst(models.Model):

    dvcName                 = models.CharField( max_length = 30 )                       #機器名

    dvcKind                 = models.CharField( max_length = 15, null = True, blank = True )          #種類

    dvcMaker                = models.CharField( max_length = 30, null = True, blank = True )          #メーカー

    dvcModel                = models.CharField( max_length = 30, null = True, blank = True )          #型番

    dvcPurchase             = models.DateField( null = True, blank = True )                           #購入日

    dvcWarranty             = models.DateField( null = True, blank = True )                           #保証期限

    dvcUser                 = models.CharField( max_length = 15, null = True, blank = True )          #使用者

    dvcPlace                = models.CharField( max_length = 30, null = True, blank = True )          #設置場所

    dvcAssetnumber          = models.CharField( max_length = 30, null = True, blank = True )          #資産番号

    dvcStatus               = models.CharField( max_length = 15, null = True, blank = True )          #使用可否

    dvcSerialnumber         = models.CharField( max_length = 30, null = True, blank = True )          #シリアル番号

    dvcOS                   = models.CharField( max_length = 15, null = True, blank = True )          #OS

    dvcCPU                  = models.CharField( max_length = 15, null = True, blank = True )          #CPU

    dvcRAM                  = models.CharField( max_length = 15, null = True, blank = True )          #RAM

    dvcGraphic              = models.CharField( max_length = 15, null = True, blank = True )          #グラフィックカード

    dvcStorage              = models.CharField( max_length = 15, null = True, blank = True )          #ストレージ

    dvcIP                   = models.CharField( max_length = 30, null = True, blank = True )          #IPアドレス

    dvcNetWork              = models.CharField( max_length = 30, null = True, blank = True )          #ネットワーク

    dvcNotes                = models.CharField( max_length = 200, null = True, blank = True )         #備考欄

    dvcDeleteFlag           = models.BooleanField( default = False )                    #削除フラグ

    #----------------------外部キー----------------------#

    #顧客名
    dvcCustomer             = models.ForeignKey( 'UserMst', 
                                                on_delete = models.CASCADE,
                                                related_name = 'dvc_usr_id',
                                                null = True,
                                                blank = True
                                                ) 

    def __str__(self):
        return str( self.id ) + '[' + str( self.dvcDeleteFlag ) +']' + ( self.dvcName )
    
class DeviceSoftMst(models.Model):

    dvsSoftName         = models.CharField( max_length = 30 )                       #ソフト名

    dvsWarranty         = models.DateField()                                        #保証期限

    dvsDeleteFlag       = models.BooleanField( default = False )                    #削除フラグ

    #----------------------外部キー----------------------#

    #機器ID
    dvsDeviceID         = models.ForeignKey( 'DeviceMst', 
                                                on_delete = models.CASCADE,
                                                related_name = 'dvs_dvc_id'
                                                )   
           

    def __str__(self):
        return str( self.id ) + '[' + str( self.dvsDeleteFlag ) +']' + ( self.dvsSoftName )








#------------------------------------------------------------------------------------------------#

Device/views.py
from django.shortcuts import render

# Create your views here.

Device/templates/Admin_Manage.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" 
      rel="stylesheet" 
      integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" 
      crossorigin="anonymous">

<div class="d-flex align-items-center justify-content-center ">
  <form action="{% url 'manage_admin' intUsr=User.id %}" method="post"  style="min-width: 400px;">
    {% csrf_token %}
    
    <div class="fs-4 text-center mb-4">
      <h1>顧客管理</h1>
    </div>

    <div class="d-flex flex-column align-items-center gap-5 m-3">

    <div class="row mb-3">
      <label class="col-4 col-form-label text-end">顧客名：</label>
      <div class="col-8">
        {{ Form.chrName }}
      </div>
    </div>

    <div class="row mb-3">
      <label class="col-4 col-form-label text-end">ログインID：</label>
      <div class="col-8">
        {{ Form.chrLoginID }}
      </div>
    </div>

    <div class="row mb-3">
      <label class="col-4 col-form-label text-end">パスワード：</label>
      <div class="col-8">
        {{ Form.chrPassWord }}
      </div>
    </div>


    <div class="row mb-3">
      <label class="col-4 col-form-label text-end">機器配置図：</label>
      <div class="col-8">
       <!-- {{ Form.chrPassWord }}-->
      </div>
    </div>

    <button class="btn btn-primary w-100" type="submit" name="btnCreate">登録</button>


    

    <button class="btn btn-danger w-100" type="submit" name="btnBack">戻る</button>

    <button class="btn btn-danger w-100" type="submit" name="btnLogout">ログアウト</button>

    
  </form>
</div>
<br>    
<br>
<br>
<br>
<br>
{% endblock %}

Device/templates/Create_Device.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"
      rel="stylesheet" crossorigin="anonymous">

<div class="container" style="max-width:1200px;">
  <!-- メインフォーム -->
  <form id="mainForm" action="{% url 'create_device' struserid=struserid %}" method="post">
    {% csrf_token %}

    <div class="fs-4 text-center mb-4">
      <h1>機器登録</h1>
    </div>

    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{ message.tags }} text-center">{{ message }}</div>
      {% endfor %}
    {% endif %}

    <!-- 入力フォーム -->
    <div class="row mb-3">
      <label class="col-2 text-end">機器名：</label>
      <div class="col-4">
        <input type="text" name="chrDeviceName" class="form-control"
               value="{{ temp_device.chrDeviceName|default:'' }}">
      </div>
      <label class="col-2 text-end">使用可否：</label>
      <div class="col-4">
        <input type="text" name="chrDeviceStatus" class="form-control"
               value="{{ temp_device.chrDeviceStatus|default:'' }}">
      </div>
    </div>

    <div class="row mb-3">
      <label class="col-2 text-end">顧客名：</label>
      <div class="col-4">
        <select name="intCustomer" class="form-select" required>
          <option value="">選択してください</option>
          {% for customer in customers %}
            <option value="{{ customer.id }}"
              {% if temp_device.intCustomer == customer.id|stringformat:"s" %}selected{% endif %}>
              {{ customer.usrName }}
            </option>
          {% endfor %}
        </select>
      </div>
      <label class="col-2 text-end">シリアル番号：</label>
      <div class="col-4">
        <input type="text" name="chrDeviceSerialNumber" class="form-control"
               value="{{ temp_device.chrDeviceSerialNumber|default:'' }}">
      </div>
    </div>

    <div class="row mb-3">
      <label class="col-2 text-end">媒体：</label>
      <div class="col-4"><input type="text" name="chrDeviceKind" class="form-control"
                                value="{{ temp_device.chrDeviceKind|default:'' }}"></div>
      <label class="col-2 text-end">OS：</label>
      <div class="col-4"><input type="text" name="chrDeviceOS" class="form-control"
                                value="{{ temp_device.chrDeviceOS|default:'' }}"></div>
    </div>

    <div class="row mb-3">
      <label class="col-2 text-end">メーカー：</label>
      <div class="col-4"><input type="text" name="chrDeviceMaker" class="form-control"
                                value="{{ temp_device.chrDeviceMaker|default:'' }}"></div>
      <label class="col-2 text-end">CPU：</label>
      <div class="col-4"><input type="text" name="chrDeviceCPU" class="form-control"
                                value="{{ temp_device.chrDeviceCPU|default:'' }}"></div>
    </div>

    <div class="row mb-3">
      <label class="col-2 text-end">型番：</label>
      <div class="col-4"><input type="text" name="chrDeviceModel" class="form-control"
                                value="{{ temp_device.chrDeviceModel|default:'' }}"></div>
      <label class="col-2 text-end">RAM：</label>
      <div class="col-4"><input type="text" name="chrDeviceRAM" class="form-control"
                                value="{{ temp_device.chrDeviceRAM|default:'' }}"></div>
    </div>

    <div class="row mb-3">
      <label class="col-2 text-end">購入日：</label>
      <div class="col-4"><input type="date" name="dtDevicePurchase" class="form-control"
                                value="{{ temp_device.dtDevicePurchase|default:'' }}"></div>
      <label class="col-2 text-end">グラフィックカード：</label>
      <div class="col-4"><input type="text" name="chrDeviceGraphic" class="form-control"
                                value="{{ temp_device.chrDeviceGraphic|default:'' }}"></div>
    </div>

    <div class="row mb-3">
      <label class="col-2 text-end">保証期限：</label>
      <div class="col-4"><input type="date" name="dtDeviceWarranty" class="form-control"
                                value="{{ temp_device.dtDeviceWarranty|default:'' }}"></div>
      <label class="col-2 text-end">ストレージ：</label>
      <div class="col-4"><input type="text" name="chrDeviceStorage" class="form-control"
                                value="{{ temp_device.chrDeviceStorage|default:'' }}"></div>
    </div>

    <div class="row mb-3">
      <label class="col-2 text-end">使用者：</label>
      <div class="col-4"><input type="text" name="chrDeviceUser" class="form-control"
                                value="{{ temp_device.chrDeviceUser|default:'' }}"></div>
      <label class="col-2 text-end">IPアドレス：</label>
      <div class="col-4"><input type="text" name="chrDeviceIP" class="form-control"
                                value="{{ temp_device.chrDeviceIP|default:'' }}"></div>
    </div>

    <div class="row mb-3">
      <label class="col-2 text-end">設置場所：</label>
      <div class="col-4"><input type="text" name="chrDevicePlace" class="form-control"
                                value="{{ temp_device.chrDevicePlace|default:'' }}"></div>
      <label class="col-2 text-end">ネットワーク：</label>
      <div class="col-4"><input type="text" name="chrDeviceNetwork" class="form-control"
                                value="{{ temp_device.chrDeviceNetwork|default:'' }}"></div>
    </div>

    <div class="row mb-3">
      <label class="col-2 text-end">資産番号：</label>
      <div class="col-4"><input type="text" name="chrDeviceAssetNumber" class="form-control"
                                value="{{ temp_device.chrDeviceAssetNumber|default:'' }}"></div>
      <label class="col-2 text-end">ソフト登録：</label>
      <div class="col-4">
        <button type="button" class="btn btn-info btn-sm w-100"
                data-bs-toggle="modal" data-bs-target="#softwareModal">
          ソフト登録
        </button>
      </div>
    </div>

    <div class="row mb-4">
      <label class="col-2 text-end">備考：</label>
      <div class="col-10"><textarea name="chrNotes" class="form-control">{{ temp_device.chrNotes|default:'' }}</textarea></div>
    </div>

    <div class="d-flex flex-column align-items-center gap-3 mb-5" style="max-width: 250px; margin: 0 auto;">
      <button class="btn btn-primary w-100" type="submit" name="btnCreate">登録</button>
      <button class="btn btn-secondary w-100" type="submit" name="btnBack" formnovalidate>戻る</button>
      <button class="btn btn-danger w-100" type="submit" name="btnLogout" formnovalidate>ログアウト</button>
    </div>
  </form>
</div>

<!-- ソフト登録モーダル -->
<div class="modal fade" id="softwareModal" tabindex="-1" aria-labelledby="softwareModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">ソフト登録</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="閉じる"></button>
      </div>
      <div class="modal-body">

        {% if temp_softs %}
          <table class="table table-bordered">
            <thead>
              <tr><th>ソフト名</th><th>保証期限</th><th>操作</th></tr>
            </thead>
            <tbody>
              {% for soft in temp_softs %}
              <tr>
                <form method="post" action="{% url 'create_device' struserid=struserid %}" class="softForm">
                  {% csrf_token %}
                  <td><input type="text" name="chrSoftName" value="{{ soft.name }}" class="form-control"></td>
                  <td><input type="date" name="chrWarranty" value="{{ soft.warranty }}" class="form-control"></td>
                  <td>
                    <input type="hidden" name="soft_index" value="{{ forloop.counter0 }}">
                    <button type="submit" name="btnUpdateSoftTemp" class="btn btn-success btn-sm">保存</button>
                    <button type="submit" name="btnDeleteSoftTemp" class="btn btn-danger btn-sm">削除</button>
                  </td>
                </form>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        {% else %}
          <p class="text-muted">登録されたソフトはありません。</p>
        {% endif %}

        <hr>

        <!-- 新規追加フォーム -->
        <form method="post" action="{% url 'create_device' struserid=struserid %}" class="softForm">
          {% csrf_token %}
          <div class="row mb-3">
            <div class="col-5"><input type="text" name="chrSoftName" class="form-control" placeholder="ソフト名"></div>
            <div class="col-5"><input type="date" name="chrWarranty" class="form-control"></div>
            <div class="col-2"><button type="submit" name="btnAddSoftTemp" class="btn btn-primary w-100">追加</button></div>
          </div>
        </form>

      </div>
    </div>
  </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>

<!-- ★ メインフォーム内容をモーダルフォームに自動コピー -->
<script>
document.querySelectorAll('.softForm').forEach(form => {
  form.addEventListener('submit', function() {
    const mainForm = document.querySelector('#mainForm');
    const inputs = mainForm.querySelectorAll('input, select, textarea');
    inputs.forEach(input => {
      if (!input.name) return;
      const hidden = document.createElement('input');
      hidden.type = 'hidden';
      hidden.name = input.name;
      hidden.value = input.value;
      this.appendChild(hidden);
    });
  });
});
</script>

{% endblock %}

Device/templates/Detail_Device.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" 
      rel="stylesheet" crossorigin="anonymous">

<div class="d-flex align-items-center justify-content-center ">
  <form action="{% url 'detail_device' struserid=struserid strdevid=strdevid %}" method="post" style="min-width: 400px;">
    {% csrf_token %}
    
    <div class="fs-4 text-center mb-4">
      <h1>詳細</h1>
    </div>

    {% if not devicesofts %}
      <div class="alert alert-danger text-center">
        ソフトが登録されていません
      </div>
    {% endif %}

    <div class="row mb-3">
      <label class="fw-bold col-3">機器名：</label>
      <div class="col-9">{{ device.dvcName }}</div>
    </div>

    <div class="row mb-3">
      <label class="fw-bold col-3">媒体：</label>
      <div class="col-9">{{ device.dvcKind }}</div>
    </div>

    <div class="row mb-3">
      <label class="fw-bold col-3">メーカー：</label>
      <div class="col-9">{{ device.dvcMaker }}</div>
    </div>

    <div class="row mb-3">
      <label class="fw-bold col-3">型番：</label>
      <div class="col-9">{{ device.dvcModel }}</div>
    </div>

    <div class="row mb-3">
      <label class="fw-bold col-3">購入日：</label>
      <div class="col-9">{{ device.dvcPurchase|date:"Y-m-d" }}</div>
    </div>

    <div class="row mb-3">
      <label class="fw-bold col-3">保証期限：</label>
      <div class="col-9">{{ device.dvcWarranty|date:"Y-m-d" }}</div>
    </div>

    <div class="row mb-3">
      <label class="fw-bold col-3">使用者：</label>
      <div class="col-9">{{ device.dvcUser }}</div>
    </div>

    <div class="row mb-3">
      <label class="fw-bold col-3">設置場所：</label>
      <div class="col-9">{{ device.dvcPlace }}</div>
    </div>

    {% if devicesofts %}
      <!-- モーダルを開くボタン -->
      <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#softModal">
        ソフト詳細
      </button>
    {% endif %}

    <div class="mb-3 col-4">
      <label class="fw-bold col-8">備考欄：</label>
      <div style="white-space: pre-wrap;">{{ device.dvcNotes }}</div>
    </div>

    <!-- モーダル -->
    <div class="modal fade" id="softModal" tabindex="-1" aria-labelledby="softModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-lg">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="softModalLabel">ソフト一覧</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="閉じる"></button>
          </div>
          <div class="modal-body">
            <table class="table table-bordered table-striped">
              <thead>
                <tr>
                  <th>ソフト名</th>
                  <th>保証期限</th>
                </tr>
              </thead>
              <tbody>
                {% for soft in devicesofts %}
                <tr>
                  <td>{{ soft.dvsSoftName }}</td>
                  <td>{{ soft.dvsWarranty|date:"Y-m-d" }}</td>
                </tr>
                {% empty %}
                <tr><td colspan="2">ソフトは登録されていません</td></tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">閉じる</button>
          </div>
        </div>
      </div>
    </div>

    <button class="btn btn-secondary w-100 mb-3" type="submit" name="btnBack">戻る</button>
    <button class="btn btn-danger w-100" type="submit" name="btnLogout">ログアウト</button>
  </form>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>

{% endblock %}

Device/templates/Home_Admin.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" 
      rel="stylesheet" 
      integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" 
      crossorigin="anonymous">

<div class="d-flex align-items-center justify-content-center ">
  <form action="{% url 'home_admin' struserid=User.id %}" method="post"  style="min-width: 400px;">
    {% csrf_token %}
    
    <div class="fs-4 text-center mb-4">
      <h1>ホーム</h1>
    </div>

    <div class="d-flex flex-column align-items-center gap-5 m-3">
        <button class="btn btn-primary w-100" type="submit" name="btnCustomer">顧客管理</button>
        <button class="btn btn-primary w-100" type="submit" name="btnDevice">機器管理</button>
        <button class="btn btn-primary w-100" type="submit" name="btnAdmin">管理者管理</button>
        <button class="btn btn-danger w-100" type="submit" name="btnLogout">ログアウト</button>
    </div>
    
  </form>
</div>
<br>    
<br>
<br>
<br>
<br>
{% endblock %}

Device/templates/Manage_Device.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" 
      rel="stylesheet" 
      integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" 
      crossorigin="anonymous">

<div class="d-flex align-items-center justify-content-center ">
  <form action="{% url 'manage_device' struserid=struserid %}" method="post" style="min-width: 900px;">
    {% csrf_token %}

    <!-- タイトル -->
    <div class="fs-4 text-center mb-4">
      <h1>機器管理</h1>
    </div>

    <!-- メッセージ表示 -->
    {% if error_customer %}
      <div class="alert alert-danger text-center">顧客を選択してください</div>
    {% endif %}
    {% if error_device %}
      <div class="alert alert-success text-center">機器が登録されていません</div>
    {% endif %}
    {% if error_software %}
      <div class="alert alert-danger text-center">ソフトが登録されていません</div>
    {% endif %}

    <!-- 顧客選択と検索 -->
    <div class="row mb-3">
      <div class="col-md-6">
        <select class="form-select" name="customer_id">
          <option value="">顧客を選択してください</option>
          {% for customer in customers %}
          <option value="{{ customer.id }}"
            {% if SelectedCustomer and customer.id == SelectedCustomer.id %}
              selected
            {% endif %}
          >
            {{ customer.usrName }}
          </option>
          {% endfor %}
        </select>
      </div>
      <div class="col-md-2">
        <button class="btn btn-secondary w-100" type="submit" name="btnSearch">検索</button>
      </div>
      <div class="col-md-4 text-end">
        <button class="btn btn-primary w-50" type="submit" name="btnCreate">登録</button>
      </div>
    </div>

    <!-- 機器一覧テーブル -->
    <div class="container mt-4">
      <table class="table table-bordered table-striped text-center">
        <thead>
          <tr>
            <th>機器名</th>
            <th>媒体</th>
            <th>購入日</th>
            <th>使用者</th>
            <th>設置場所</th>
            <th>ソフト確認</th>
            <th>編集</th>
            <th>削除</th>
          </tr>
        </thead>
        <tbody>
          {% for device in Devices %}
          <tr>
              <td>{{ device.dvcName }}</td>
              <td>{{ device.get_dvcKind_display }}</td>
              <td>{{ device.dvcPurchase }}</td>
              <td>{{ device.dvcUser }}</td>
              <td>{{ device.dvcPlace }}</td>
            <td>
              <button type="submit"
                      class="btn btn-info btn-sm mb-3"
                      name="btnCheckSoftware"
                      value="{{ device.id }}"
                      formnovalidate
                      {% if not device.has_software %}disabled{% endif %}>
                確認
              </button>
            </td>
            <td>
              <button type="submit" class="btn btn-warning btn-sm" name="btnEdit" value="{{ device.id }}" >編集</button>
            </td>
            <td>
              <button type="submit" class="btn btn-danger btn-sm" name="btnDelete" value="{{ device.id }}" formnovalidate>削除</button>
            </td>
          </tr>
          {% empty %}
          <tr>
            <td colspan="8">機器が登録されていません</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>

    <!-- ソフト一覧モーダル -->
    <div class="modal fade" id="softwareModal" tabindex="-1" aria-labelledby="softwareModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-lg">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="softwareModalLabel">ソフト一覧</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="閉じる"></button>
          </div>
          <div class="modal-body">
            {% if softwares %}
            <table class="table table-bordered table-striped text-center">
              <thead>
                <tr>
                  <th>ソフト名</th>
                  <th>保証期限</th>
                </tr>
              </thead>
              <tbody>
                {% for sw in softwares %}
                <tr>
                  <td>{{ sw.dvsSoftName }}</td>
                  <td>{{ sw.dvsWarranty|date:"Y-m-d" }}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
            {% else %}
            <div class="alert alert-warning text-center">
              ソフトが登録されていません
            </div>
            {% endif %}
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">閉じる</button>
          </div>
        </div>
      </div>
    </div>
        <input type="hidden" name="selected_customer_id" value="{{ SelectedCustomer.id }}">
        <div class="d-flex flex-column align-items-center gap-4 mb-5" style="max-width: 400px; margin: auto;">
          <button class="btn btn-primary w-50"
                  type="submit"
                  name="btnOutput"
                  {% if not can_output %}disabled{% endif %}>
            出力
          </button>
          <button class="btn btn-secondary w-50" type="submit" name="btnBack" formnovalidate>戻る</button>
          <button class="btn btn-danger w-50" type="submit" name="btnLogout" formnovalidate>ログアウト</button>
        </div>

  </form>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>

{% if open_modal %}
<script>
  document.addEventListener("DOMContentLoaded", function() {
    var myModal = new bootstrap.Modal(document.getElementById('softwareModal'));
    myModal.show();
  });
</script>
{% endif %}

{% endblock %}